pkgdown::build_site(run_dont_run = TRUE, lazy = TRUE)
system('echo "www.rayshader.com" >> docs/CNAME')
system("git checkout -b gh-pages")
system("git add -f docs")
system('git commit -m "deploy to gh-pages"')
system("git push origin `git subtree split --prefix docs`:gh-pages --force")
system("git checkout master")
system("git branch -D gh-pages")
