#'@title Get the Extent for a 3D ggplot Scene
#'
#'@description Returns the synthetic extent generated by the most recent [plot_gg()] call.
#'This extent maps the plotted x/y data range into the full rasterized ggplot scene, which
#'allows post-hoc overlays to be added with functions such as [render_points()] or [render_path()].
#'
#'@param heightmap Default `NULL`. A height matrix previously returned by [plot_gg()] with
#'`save_height_matrix = TRUE`. If supplied, the extent metadata will be read from the matrix
#'instead of the active 3D scene.
#'@param panel Default `NULL`. Panel index to return for faceted ggplots. If left `NULL` and the
#'scene contains a single panel, a single extent vector is returned. If multiple panels are present,
#'a named list of extents is returned.
#'
#'@return A named numeric vector with `xmin`, `xmax`, `ymin`, and `ymax`, or a named list of those
#'vectors for multi-panel plots.
#'@export
#'
#'@examples
#'if(run_documentation()) {
#'library(ggplot2)
#'
#'mtplot = ggplot(mtcars) +
#'  geom_point(aes(x = wt, y = mpg, color = mpg))
#'
#'plot_gg(mtplot, width = 4, windowsize = c(1000, 800))
#'gg_extent = get_ggplot_extent()
#'
#'render_points(
#'	long = mtcars$wt,
#'	lat = mtcars$mpg,
#'	altitude = mtcars$disp+150,
#'	color = "red",
#'	size = 6,
#'	extent = gg_extent,
#'	clear_previous = T
#')
#'render_snapshot()
#'}
get_ggplot_extent = function(heightmap = NULL, panel = NULL) {
	panel_info = NULL
	if (!is.null(heightmap)) {
		panel_info = attr(heightmap, "ggplot_panel_info", exact = TRUE)
	}
	if (is.null(panel_info)) {
		panel_info = get0(
			"plot_gg_panel_info",
			envir = ray_cache_scene_envir,
			inherits = FALSE
		)
	}
	if (is.null(panel_info) || !nrow(panel_info)) {
		stop("No cached ggplot extent found. Call `plot_gg()` first.")
	}

	build_extent = function(info_row) {
		extent = c(
			xmin = info_row$extent_xmin,
			xmax = info_row$extent_xmax,
			ymin = info_row$extent_ymin,
			ymax = info_row$extent_ymax
		)
		attr(extent, "panel_info") = info_row
		extent
	}

	if (!is.null(panel)) {
		match_index = match(panel, panel_info$panel)
		if (is.na(match_index)) {
			stop(sprintf(
				"Could not find panel `%s`. Available panels: %s",
				as.character(panel),
				paste(panel_info$panel, collapse = ", ")
			))
		}
		return(build_extent(panel_info[match_index, , drop = FALSE]))
	}

	if (nrow(panel_info) == 1) {
		return(build_extent(panel_info[1, , drop = FALSE]))
	}

	extents = lapply(seq_len(nrow(panel_info)), function(i) {
		build_extent(panel_info[i, , drop = FALSE])
	})
	names(extents) = paste0("panel_", panel_info$panel)
	attr(extents, "panel_info") = panel_info
	extents
}

get_ggplot_panel_range = function(panel_params, axis = c("x", "y")) {
	axis = match.arg(axis)
	range_candidates = c(
		paste0(axis, ".range"),
		paste0(axis, "_range")
	)
	for (candidate in range_candidates) {
		candidate_val = panel_params[[candidate]]
		if (!is.null(candidate_val)) {
			return(as.numeric(candidate_val))
		}
	}
	axis_info = panel_params[[axis]]
	if (!is.null(axis_info$continuous_range)) {
		return(as.numeric(axis_info$continuous_range))
	}
	if (!is.null(axis_info$range$range)) {
		return(as.numeric(axis_info$range$range))
	}
	stop(sprintf(
		"Could not determine panel %s range from ggplot build object.",
		axis
	))
}

get_ggplot_panel_viewport = function(panel_layout_row) {
	sprintf(
		"%s.%s-%s-%s-%s",
		panel_layout_row$name,
		panel_layout_row$t,
		panel_layout_row$l,
		panel_layout_row$b,
		panel_layout_row$r
	)
}

get_device_panel_bbox = function(width_px, height_px) {
	bbox_in = c(
		unlist(grid::deviceLoc(grid::unit(0, "npc"), grid::unit(0, "npc"), TRUE)),
		unlist(grid::deviceLoc(grid::unit(1, "npc"), grid::unit(1, "npc"), TRUE))
	)
	dev_size_in = grDevices::dev.size("in")
	bbox_px = bbox_in
	bbox_px[c(1, 3)] = bbox_px[c(1, 3)] / dev_size_in[1] * width_px
	bbox_px[c(2, 4)] = bbox_px[c(2, 4)] / dev_size_in[2] * height_px
	bbox_px[c(2, 4)] = height_px - bbox_px[c(4, 2)]
	stats::setNames(as.numeric(bbox_px), c("xmin", "ymin", "xmax", "ymax"))
}

expand_ggplot_x_extent = function(data_range, panel_range, scene_width) {
	slope = diff(data_range) / diff(panel_range)
	c(
		xmin = data_range[1] - (panel_range[1] - 1) * slope,
		xmax = data_range[2] + (scene_width - panel_range[2]) * slope
	)
}

expand_ggplot_y_extent = function(data_range, panel_range, scene_height) {
	slope = diff(data_range) / diff(panel_range)
	c(
		ymin = data_range[1] - (scene_height - panel_range[2]) * slope,
		ymax = data_range[2] + (panel_range[1] - 1) * slope
	)
}

cache_plot_gg_panel_info = function(panel_info = NULL) {
	assign("plot_gg_panel_info", panel_info, envir = ray_cache_scene_envir)
}

capture_plot_gg_panel_info = function(
	ggplot_grob,
	ggplot_build_obj,
	original_width_px,
	original_height_px
) {
	panel_layout = ggplot_grob$layout[grepl("^panel", ggplot_grob$layout$name), ]
	panel_params = ggplot_build_obj$layout$panel_params
	build_layout = ggplot_build_obj$layout$layout

	if (!nrow(panel_layout)) {
		return(NULL)
	}
	if (nrow(build_layout) == 1 && any(panel_layout$name == "panel")) {
		panel_layout = panel_layout[
			match("panel", panel_layout$name),
			,
			drop = FALSE
		]
	} else if (all(c("ROW", "COL") %in% colnames(build_layout))) {
		expected_panel_names = paste0(
			"panel-",
			as.integer(as.character(build_layout$COL)),
			"-",
			as.integer(as.character(build_layout$ROW))
		)
		panel_layout = panel_layout[
			match(expected_panel_names, panel_layout$name),
			,
			drop = FALSE
		]
	}
	if (anyNA(panel_layout$name)) {
		warning(
			"Unable to cache ggplot extent: could not match panel grobs to ggplot layout."
		)
		return(NULL)
	}
	if (nrow(panel_layout) != length(panel_params)) {
		warning(
			"Unable to cache ggplot extent: panel layout and panel parameter counts differ."
		)
		return(NULL)
	}

	grid::grid.force()
	panel_info = vector("list", length(panel_params))
	for (i in seq_along(panel_params)) {
		panel_vp = get_ggplot_panel_viewport(panel_layout[i, , drop = FALSE])
		grid::seekViewport(panel_vp)
		bbox_orig = get_device_panel_bbox(original_width_px, original_height_px)
		grid::upViewport(0)

		x_range = get_ggplot_panel_range(panel_params[[i]], "x")
		y_range = get_ggplot_panel_range(panel_params[[i]], "y")

		panel_info[[i]] = data.frame(
			panel = as.integer(as.character(build_layout$PANEL[i])),
			row = if ("ROW" %in% colnames(build_layout)) {
				as.integer(as.character(build_layout$ROW[i]))
			} else {
				NA_integer_
			},
			col = if ("COL" %in% colnames(build_layout)) {
				as.integer(as.character(build_layout$COL[i]))
			} else {
				NA_integer_
			},
			panel_name = panel_layout$name[i],
			viewport_name = panel_vp,
			data_xmin = x_range[1],
			data_xmax = x_range[2],
			data_ymin = y_range[1],
			data_ymax = y_range[2],
			panel_xmin = bbox_orig["xmin"],
			panel_xmax = bbox_orig["xmax"],
			panel_ymin = bbox_orig["ymin"],
			panel_ymax = bbox_orig["ymax"]
		)
	}
	do.call("rbind", panel_info)
}

finalize_plot_gg_panel_info = function(
	panel_info,
	original_width_px,
	original_height_px,
	scene_width_px,
	scene_height_px
) {
	if (is.null(panel_info) || !nrow(panel_info)) {
		return(panel_info)
	}

	panel_info$panel_xmin = panel_info$panel_xmin /
		original_width_px *
		scene_width_px
	panel_info$panel_xmax = panel_info$panel_xmax /
		original_width_px *
		scene_width_px
	panel_info$panel_ymin = panel_info$panel_ymin /
		original_height_px *
		scene_height_px
	panel_info$panel_ymax = panel_info$panel_ymax /
		original_height_px *
		scene_height_px

	for (i in seq_len(nrow(panel_info))) {
		extent_x = expand_ggplot_x_extent(
			c(panel_info$data_xmin[i], panel_info$data_xmax[i]),
			c(panel_info$panel_xmin[i], panel_info$panel_xmax[i]),
			scene_width_px
		)
		extent_y = expand_ggplot_y_extent(
			c(panel_info$data_ymin[i], panel_info$data_ymax[i]),
			c(panel_info$panel_ymin[i], panel_info$panel_ymax[i]),
			scene_height_px
		)
		panel_info$extent_xmin[i] = extent_x["xmin"]
		panel_info$extent_xmax[i] = extent_x["xmax"]
		panel_info$extent_ymin[i] = extent_y["ymin"]
		panel_info$extent_ymax[i] = extent_y["ymax"]
	}
	panel_info
}
