# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bilineargrid <- function(colorarray) {
    .Call(`_rayshader_bilineargrid`, colorarray)
}

calculate_normal_cpp <- function(heightmap, progbar) {
    .Call(`_rayshader_calculate_normal_cpp`, heightmap, progbar)
}

construct_matrix <- function(image_reference, number_rows, number_cols, index_x, index_y) {
    .Call(`_rayshader_construct_matrix`, image_reference, number_rows, number_cols, index_x, index_y)
}

fill_find_groups <- function(max_z_matrix) {
    .Call(`_rayshader_fill_find_groups`, max_z_matrix)
}

find_groups_cpp <- function(max_z_matrix) {
    .Call(`_rayshader_find_groups_cpp`, max_z_matrix)
}

interpolate_color <- function(color_nw, color_ne, color_se, color_sw) {
    .Call(`_rayshader_interpolate_color`, color_nw, color_ne, color_se, color_sw)
}

lambshade_cpp <- function(heightmap, rayvector) {
    .Call(`_rayshader_lambshade_cpp`, heightmap, rayvector)
}

make_surface_cpp <- function(heightmap, na_matrix, normalsx, normalsy, normalsz, basedepth) {
    .Call(`_rayshader_make_surface_cpp`, heightmap, na_matrix, normalsx, normalsy, normalsz, basedepth)
}

make_base_cpp <- function(heightmap, na_matrix, basedepth) {
    .Call(`_rayshader_make_base_cpp`, heightmap, na_matrix, basedepth)
}

make_water_cpp <- function(heightmap, na_matrix, waterheight) {
    .Call(`_rayshader_make_water_cpp`, heightmap, na_matrix, waterheight)
}

make_waterlines_cpp <- function(heightmap, na_matrix, waterdepth) {
    .Call(`_rayshader_make_waterlines_cpp`, heightmap, na_matrix, waterdepth)
}

make_baselines_cpp <- function(heightmap, na_matrix, waterdepth) {
    .Call(`_rayshader_make_baselines_cpp`, heightmap, na_matrix, waterdepth)
}

subsample <- function(circle, size) {
    .Call(`_rayshader_subsample`, circle, size)
}

subsample_rect <- function(rect, binsx, binsy) {
    .Call(`_rayshader_subsample_rect`, rect, binsx, binsy)
}

gen_circle_psf <- function(radius) {
    .Call(`_rayshader_gen_circle_psf`, radius)
}

gen_ellipse <- function(intensity, width, height) {
    .Call(`_rayshader_gen_ellipse`, intensity, width, height)
}

is_inside <- function(sizehex, positionx, positiony, sinval, cosval) {
    .Call(`_rayshader_is_inside`, sizehex, positionx, positiony, sinval, cosval)
}

gen_hex_psf <- function(radius, rotation) {
    .Call(`_rayshader_gen_hex_psf`, radius, rotation)
}

psf <- function(image, blurmatrix, depthmap, depth, custombokeh, type, bokehintensity, bokehlimit, rotation, progbar, channel) {
    .Call(`_rayshader_psf`, image, blurmatrix, depthmap, depth, custombokeh, type, bokehintensity, bokehlimit, rotation, progbar, channel)
}

rayshade_cpp <- function(sunangle, anglebreaks, heightmap, zscale, maxsearch, cache_mask, progbar) {
    .Call(`_rayshader_rayshade_cpp`, sunangle, anglebreaks, heightmap, zscale, maxsearch, cache_mask, progbar)
}

rayshade_multicore <- function(sunangle, anglebreaks, heightmap, zscale, chunkindices, maxsearch, cache_mask) {
    .Call(`_rayshader_rayshade_multicore`, sunangle, anglebreaks, heightmap, zscale, chunkindices, maxsearch, cache_mask)
}

