# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lambshade_cpp <- function(heightmap, rayvector) {
    .Call(`_rayshader_lambshade_cpp`, heightmap, rayvector)
}

rayshade_multicore <- function(sunangle, anglebreaks, heightmap, zscale, maxsearch, row) {
    .Call(`_rayshader_rayshade_multicore`, sunangle, anglebreaks, heightmap, zscale, maxsearch, row)
}

rayshade_cpp <- function(sunangle, anglebreaks, heightmap, zscale, maxsearch) {
    .Call(`_rayshader_rayshade_cpp`, sunangle, anglebreaks, heightmap, zscale, maxsearch)
}

