# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bilineargrid <- function(colorarray) {
    .Call(`_rayshader_bilineargrid`, colorarray)
}

calculate_normal_cpp <- function(heightmap, progbar) {
    .Call(`_rayshader_calculate_normal_cpp`, heightmap, progbar)
}

construct_matrix <- function(image_reference, number_rows, number_cols, index_x, index_y) {
    .Call(`_rayshader_construct_matrix`, image_reference, number_rows, number_cols, index_x, index_y)
}

fill_find_groups <- function(max_z_matrix) {
    .Call(`_rayshader_fill_find_groups`, max_z_matrix)
}

find_groups_cpp <- function(max_z_matrix) {
    .Call(`_rayshader_find_groups_cpp`, max_z_matrix)
}

interpolate_color <- function(color_nw, color_ne, color_se, color_sw) {
    .Call(`_rayshader_interpolate_color`, color_nw, color_ne, color_se, color_sw)
}

lambshade_cpp <- function(heightmap, rayvector) {
    .Call(`_rayshader_lambshade_cpp`, heightmap, rayvector)
}

make_surface_cpp <- function(heightmap, na_matrix, normalsx, normalsy, normalsz, basedepth) {
    .Call(`_rayshader_make_surface_cpp`, heightmap, na_matrix, normalsx, normalsy, normalsz, basedepth)
}

make_base_cpp <- function(heightmap, na_matrix, basedepth) {
    .Call(`_rayshader_make_base_cpp`, heightmap, na_matrix, basedepth)
}

make_water_cpp <- function(heightmap, na_matrix, waterheight) {
    .Call(`_rayshader_make_water_cpp`, heightmap, na_matrix, waterheight)
}

make_water_mesh_cpp <- function(heightmap, waterheight) {
    .Call(`_rayshader_make_water_mesh_cpp`, heightmap, waterheight)
}

make_waterlines_cpp <- function(heightmap, na_matrix, waterdepth) {
    .Call(`_rayshader_make_waterlines_cpp`, heightmap, na_matrix, waterdepth)
}

make_baselines_cpp <- function(heightmap, na_matrix, waterdepth) {
    .Call(`_rayshader_make_baselines_cpp`, heightmap, na_matrix, waterdepth)
}

cubic_interpolate <- function(p0, p1, p2, p3, x) {
    .Call(`_rayshader_cubic_interpolate`, p0, p1, p2, p3, x)
}

bicubic_interpolate <- function(p, x, y) {
    .Call(`_rayshader_bicubic_interpolate`, p, x, y)
}

subsample <- function(circle, size) {
    .Call(`_rayshader_subsample`, circle, size)
}

subsample_rect <- function(rect, binsx, binsy) {
    .Call(`_rayshader_subsample_rect`, rect, binsx, binsy)
}

gen_circle_psf <- function(radius) {
    .Call(`_rayshader_gen_circle_psf`, radius)
}

gen_ellipse <- function(intensity, width, height) {
    .Call(`_rayshader_gen_ellipse`, intensity, width, height)
}

is_inside <- function(sizehex, positionx, positiony, sinval, cosval) {
    .Call(`_rayshader_is_inside`, sizehex, positionx, positiony, sinval, cosval)
}

gen_hex_psf <- function(radius, rotation) {
    .Call(`_rayshader_gen_hex_psf`, radius, rotation)
}

psf <- function(image, blurmatrix, depthmap, depth, custombokeh, type, bokehintensity, bokehlimit, rotation, progbar, channel) {
    .Call(`_rayshader_psf`, image, blurmatrix, depthmap, depth, custombokeh, type, bokehintensity, bokehlimit, rotation, progbar, channel)
}

rayshade_cpp <- function(sunangle, anglebreaks, heightmap, zscale, maxsearch, cache_mask, progbar) {
    .Call(`_rayshader_rayshade_cpp`, sunangle, anglebreaks, heightmap, zscale, maxsearch, cache_mask, progbar)
}

rayshade_multicore <- function(sunangle, anglebreaks, heightmap, zscale, chunkindices, maxsearch, cache_mask) {
    .Call(`_rayshader_rayshade_multicore`, sunangle, anglebreaks, heightmap, zscale, chunkindices, maxsearch, cache_mask)
}

calculate_render_road_vertex_frames_cpp <- function(points, closed, miter_limit) {
    .Call(`_rayshader_calculate_render_road_vertex_frames_cpp`, points, closed, miter_limit)
}

densify_render_highquality_path_xz_cpp <- function(points, left_edge, right_edge, center_offset, row_count, column_count) {
    .Call(`_rayshader_densify_render_highquality_path_xz_cpp`, points, left_edge, right_edge, center_offset, row_count, column_count)
}

evaluate_render_road_profiles_cpp <- function(fragment_index, distance, control_start, control_count, control_row, control_distance, height, grade) {
    .Call(`_rayshader_evaluate_render_road_profiles_cpp`, fragment_index, distance, control_start, control_count, control_row, control_distance, height, grade)
}

audit_render_road_profiles_cpp <- function(specification_list, height, grade, tolerance, diagnostics = FALSE, maximum_requests_per_relation = 1L) {
    .Call(`_rayshader_audit_render_road_profiles_cpp`, specification_list, height, grade, tolerance, diagnostics, maximum_requests_per_relation)
}

compile_render_road_profile_problem_cpp <- function(specification_list, adaptive_list) {
    .Call(`_rayshader_compile_render_road_profile_problem_cpp`, specification_list, adaptive_list)
}

solve_render_road_profiles_cpp <- function(specification, solve_component, profile_tolerance, maximum_refinement_iterations, diagnostics = FALSE, maximum_requests_per_relation = 1L) {
    .Call(`_rayshader_solve_render_road_profiles_cpp`, specification, solve_component, profile_tolerance, maximum_refinement_iterations, diagnostics, maximum_requests_per_relation)
}

make_spatial_water_fixed_grid_terrain_mesh_cpp <- function(heightmap) {
    .Call(`_rayshader_make_spatial_water_fixed_grid_terrain_mesh_cpp`, heightmap)
}

spatial_water_face_sublevel_area_cpp <- function(terrain_mesh, face_ids, water_level, height_tol) {
    .Call(`_rayshader_spatial_water_face_sublevel_area_cpp`, terrain_mesh, face_ids, water_level, height_tol)
}

spatial_water_traverse_seeded_clipped_faces_cpp <- function(terrain_mesh, component_seed, water_level, target_area_limit, height_tol, length_tol, area_tol, return_face_ids = FALSE) {
    .Call(`_rayshader_spatial_water_traverse_seeded_clipped_faces_cpp`, terrain_mesh, component_seed, water_level, target_area_limit, height_tol, length_tol, area_tol, return_face_ids)
}

build_spatial_water_full_terrain_geometry_cpp <- function(terrain_mesh, water_level, surface_area_tol) {
    .Call(`_rayshader_build_spatial_water_full_terrain_geometry_cpp`, terrain_mesh, water_level, surface_area_tol)
}

build_spatial_water_triangle_clipped_geometry_cpp <- function(terrain_mesh, selected_face_ids, water_level, height_tol, t_tol, length_tol, area_tol, surface_area_tol) {
    .Call(`_rayshader_build_spatial_water_triangle_clipped_geometry_cpp`, terrain_mesh, selected_face_ids, water_level, height_tol, t_tol, length_tol, area_tol, surface_area_tol)
}

